fragment BlogParts on Blog {
  __typename
  title
  date
  author
  excerpt
  primaryCategory
  categories
  tags
  tones
  audio
  category
  heroImage
  body
}

fragment PagesParts on Pages {
  __typename
  hero {
    __typename
    badge
    titleLine1
    titleHighlight
    titleLine3
    subtitle
    primaryCta
    primaryCtaLink
    secondaryCta
    secondaryCtaLink
    achievements
    impactStats {
      __typename
      number
      label
    }
    callout {
      __typename
      title
      subtitle
      cta
      ctaLink
    }
  }
  stats {
    __typename
    number
    label
    description
  }
  programsSection {
    __typename
    title
    subtitle
    ctaText
    ctaLink
  }
  storiesSection {
    __typename
    title
    subtitle
    ctaText
    ctaLink
  }
  newsletter {
    __typename
    title
    subtitle
    emailPlaceholder
    buttonText
    disclaimer
  }
}

fragment ProgramsParts on Programs {
  __typename
  title
  heroImage
  body
  category
  impactMetric
  impactValue
  impactUnit
}

fragment StoriesParts on Stories {
  __typename
  title
  author
  date
  location
  image
  body
  category
  impactMetric
  impactValue
  impactUnit
}

fragment TeamParts on Team {
  __typename
  name
  title
  photo
  bio
}
