//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  blog: Blog;
  blogConnection: BlogConnection;
  pages: Pages;
  pagesConnection: PagesConnection;
  programs: Programs;
  programsConnection: ProgramsConnection;
  stories: Stories;
  storiesConnection: StoriesConnection;
  team: Team;
  teamConnection: TeamConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};


export type QueryPagesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
};


export type QueryProgramsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProgramsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProgramsFilter>;
};


export type QueryStoriesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryStoriesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StoriesFilter>;
};


export type QueryTeamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
};

export type DocumentFilter = {
  blog?: InputMaybe<BlogFilter>;
  pages?: InputMaybe<PagesFilter>;
  programs?: InputMaybe<ProgramsFilter>;
  stories?: InputMaybe<StoriesFilter>;
  team?: InputMaybe<TeamFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Blog | Pages | Programs | Stories | Team | Folder;

export type Blog = Node & Document & {
  __typename?: 'Blog';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  excerpt?: Maybe<Scalars['String']['output']>;
  primaryCategory: Scalars['String']['output'];
  categories?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tones?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  audio?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlogFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  primaryCategory?: InputMaybe<StringFilter>;
  categories?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  tones?: InputMaybe<StringFilter>;
  audio?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type PagesHeroImpactStats = {
  __typename?: 'PagesHeroImpactStats';
  number?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type PagesHeroCallout = {
  __typename?: 'PagesHeroCallout';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
};

export type PagesHero = {
  __typename?: 'PagesHero';
  badge?: Maybe<Scalars['String']['output']>;
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  titleLine3?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  primaryCta?: Maybe<Scalars['String']['output']>;
  primaryCtaLink?: Maybe<Scalars['String']['output']>;
  secondaryCta?: Maybe<Scalars['String']['output']>;
  secondaryCtaLink?: Maybe<Scalars['String']['output']>;
  achievements?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  impactStats?: Maybe<Array<Maybe<PagesHeroImpactStats>>>;
  callout?: Maybe<PagesHeroCallout>;
};

export type PagesStats = {
  __typename?: 'PagesStats';
  number?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type PagesProgramsSection = {
  __typename?: 'PagesProgramsSection';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
};

export type PagesStoriesSection = {
  __typename?: 'PagesStoriesSection';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  ctaText?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
};

export type PagesNewsletter = {
  __typename?: 'PagesNewsletter';
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  emailPlaceholder?: Maybe<Scalars['String']['output']>;
  buttonText?: Maybe<Scalars['String']['output']>;
  disclaimer?: Maybe<Scalars['String']['output']>;
};

export type Pages = Node & Document & {
  __typename?: 'Pages';
  hero?: Maybe<PagesHero>;
  stats?: Maybe<Array<Maybe<PagesStats>>>;
  programsSection?: Maybe<PagesProgramsSection>;
  storiesSection?: Maybe<PagesStoriesSection>;
  newsletter?: Maybe<PagesNewsletter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagesHeroImpactStatsFilter = {
  number?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type PagesHeroCalloutFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  cta?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type PagesHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  titleLine1?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  titleLine3?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  primaryCta?: InputMaybe<StringFilter>;
  primaryCtaLink?: InputMaybe<StringFilter>;
  secondaryCta?: InputMaybe<StringFilter>;
  secondaryCtaLink?: InputMaybe<StringFilter>;
  achievements?: InputMaybe<StringFilter>;
  impactStats?: InputMaybe<PagesHeroImpactStatsFilter>;
  callout?: InputMaybe<PagesHeroCalloutFilter>;
};

export type PagesStatsFilter = {
  number?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type PagesProgramsSectionFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type PagesStoriesSectionFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type PagesNewsletterFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  emailPlaceholder?: InputMaybe<StringFilter>;
  buttonText?: InputMaybe<StringFilter>;
  disclaimer?: InputMaybe<StringFilter>;
};

export type PagesFilter = {
  hero?: InputMaybe<PagesHeroFilter>;
  stats?: InputMaybe<PagesStatsFilter>;
  programsSection?: InputMaybe<PagesProgramsSectionFilter>;
  storiesSection?: InputMaybe<PagesStoriesSectionFilter>;
  newsletter?: InputMaybe<PagesNewsletterFilter>;
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pages>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Programs = Node & Document & {
  __typename?: 'Programs';
  title: Scalars['String']['output'];
  heroImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  impactMetric?: Maybe<Scalars['String']['output']>;
  impactValue?: Maybe<Scalars['String']['output']>;
  impactUnit?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProgramsFilter = {
  title?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
  category?: InputMaybe<StringFilter>;
  impactMetric?: InputMaybe<StringFilter>;
  impactValue?: InputMaybe<StringFilter>;
  impactUnit?: InputMaybe<StringFilter>;
};

export type ProgramsConnectionEdges = {
  __typename?: 'ProgramsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Programs>;
};

export type ProgramsConnection = Connection & {
  __typename?: 'ProgramsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProgramsConnectionEdges>>>;
};

export type Stories = Node & Document & {
  __typename?: 'Stories';
  title: Scalars['String']['output'];
  author?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  impactMetric?: Maybe<Scalars['String']['output']>;
  impactValue?: Maybe<Scalars['String']['output']>;
  impactUnit?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StoriesFilter = {
  title?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  location?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
  category?: InputMaybe<StringFilter>;
  impactMetric?: InputMaybe<StringFilter>;
  impactValue?: InputMaybe<StringFilter>;
  impactUnit?: InputMaybe<StringFilter>;
};

export type StoriesConnectionEdges = {
  __typename?: 'StoriesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Stories>;
};

export type StoriesConnection = Connection & {
  __typename?: 'StoriesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<StoriesConnectionEdges>>>;
};

export type Team = Node & Document & {
  __typename?: 'Team';
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TeamFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  bio?: InputMaybe<RichTextFilter>;
};

export type TeamConnectionEdges = {
  __typename?: 'TeamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team>;
};

export type TeamConnection = Connection & {
  __typename?: 'TeamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBlog: Blog;
  createBlog: Blog;
  updatePages: Pages;
  createPages: Pages;
  updatePrograms: Programs;
  createPrograms: Programs;
  updateStories: Stories;
  createStories: Stories;
  updateTeam: Team;
  createTeam: Team;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationUpdatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationCreatePagesArgs = {
  relativePath: Scalars['String']['input'];
  params: PagesMutation;
};


export type MutationUpdateProgramsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProgramsMutation;
};


export type MutationCreateProgramsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProgramsMutation;
};


export type MutationUpdateStoriesArgs = {
  relativePath: Scalars['String']['input'];
  params: StoriesMutation;
};


export type MutationCreateStoriesArgs = {
  relativePath: Scalars['String']['input'];
  params: StoriesMutation;
};


export type MutationUpdateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationCreateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};

export type DocumentUpdateMutation = {
  blog?: InputMaybe<BlogMutation>;
  pages?: InputMaybe<PagesMutation>;
  programs?: InputMaybe<ProgramsMutation>;
  stories?: InputMaybe<StoriesMutation>;
  team?: InputMaybe<TeamMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  blog?: InputMaybe<BlogMutation>;
  pages?: InputMaybe<PagesMutation>;
  programs?: InputMaybe<ProgramsMutation>;
  stories?: InputMaybe<StoriesMutation>;
  team?: InputMaybe<TeamMutation>;
};

export type BlogMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  primaryCategory?: InputMaybe<Scalars['String']['input']>;
  categories?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tones?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  audio?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PagesHeroImpactStatsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type PagesHeroCalloutMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type PagesHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  titleLine3?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  primaryCta?: InputMaybe<Scalars['String']['input']>;
  primaryCtaLink?: InputMaybe<Scalars['String']['input']>;
  secondaryCta?: InputMaybe<Scalars['String']['input']>;
  secondaryCtaLink?: InputMaybe<Scalars['String']['input']>;
  achievements?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  impactStats?: InputMaybe<Array<InputMaybe<PagesHeroImpactStatsMutation>>>;
  callout?: InputMaybe<PagesHeroCalloutMutation>;
};

export type PagesStatsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PagesProgramsSectionMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type PagesStoriesSectionMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type PagesNewsletterMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  emailPlaceholder?: InputMaybe<Scalars['String']['input']>;
  buttonText?: InputMaybe<Scalars['String']['input']>;
  disclaimer?: InputMaybe<Scalars['String']['input']>;
};

export type PagesMutation = {
  hero?: InputMaybe<PagesHeroMutation>;
  stats?: InputMaybe<Array<InputMaybe<PagesStatsMutation>>>;
  programsSection?: InputMaybe<PagesProgramsSectionMutation>;
  storiesSection?: InputMaybe<PagesStoriesSectionMutation>;
  newsletter?: InputMaybe<PagesNewsletterMutation>;
};

export type ProgramsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  impactMetric?: InputMaybe<Scalars['String']['input']>;
  impactValue?: InputMaybe<Scalars['String']['input']>;
  impactUnit?: InputMaybe<Scalars['String']['input']>;
};

export type StoriesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  impactMetric?: InputMaybe<Scalars['String']['input']>;
  impactValue?: InputMaybe<Scalars['String']['input']>;
  impactUnit?: InputMaybe<Scalars['String']['input']>;
};

export type TeamMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['JSON']['input']>;
};

export type BlogPartsFragment = { __typename: 'Blog', title: string, date?: string | null, author?: string | null, excerpt?: string | null, primaryCategory: string, categories?: Array<string | null> | null, tags?: Array<string | null> | null, tones?: Array<string | null> | null, audio?: string | null, category?: string | null, heroImage?: string | null, body?: any | null };

export type PagesPartsFragment = { __typename: 'Pages', hero?: { __typename: 'PagesHero', badge?: string | null, titleLine1?: string | null, titleHighlight?: string | null, titleLine3?: string | null, subtitle?: string | null, primaryCta?: string | null, primaryCtaLink?: string | null, secondaryCta?: string | null, secondaryCtaLink?: string | null, achievements?: Array<string | null> | null, impactStats?: Array<{ __typename: 'PagesHeroImpactStats', number?: string | null, label?: string | null } | null> | null, callout?: { __typename: 'PagesHeroCallout', title?: string | null, subtitle?: string | null, cta?: string | null, ctaLink?: string | null } | null } | null, stats?: Array<{ __typename: 'PagesStats', number?: string | null, label?: string | null, description?: string | null } | null> | null, programsSection?: { __typename: 'PagesProgramsSection', title?: string | null, subtitle?: string | null, ctaText?: string | null, ctaLink?: string | null } | null, storiesSection?: { __typename: 'PagesStoriesSection', title?: string | null, subtitle?: string | null, ctaText?: string | null, ctaLink?: string | null } | null, newsletter?: { __typename: 'PagesNewsletter', title?: string | null, subtitle?: string | null, emailPlaceholder?: string | null, buttonText?: string | null, disclaimer?: string | null } | null };

export type ProgramsPartsFragment = { __typename: 'Programs', title: string, heroImage?: string | null, body?: any | null, category?: string | null, impactMetric?: string | null, impactValue?: string | null, impactUnit?: string | null };

export type StoriesPartsFragment = { __typename: 'Stories', title: string, author?: string | null, date?: string | null, location?: string | null, image?: string | null, body?: any | null, category?: string | null, impactMetric?: string | null, impactValue?: string | null, impactUnit?: string | null };

export type TeamPartsFragment = { __typename: 'Team', name?: string | null, title?: string | null, photo?: string | null, bio?: any | null };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, title: string, date?: string | null, author?: string | null, excerpt?: string | null, primaryCategory: string, categories?: Array<string | null> | null, tags?: Array<string | null> | null, tones?: Array<string | null> | null, audio?: string | null, category?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, title: string, date?: string | null, author?: string | null, excerpt?: string | null, primaryCategory: string, categories?: Array<string | null> | null, tags?: Array<string | null> | null, tones?: Array<string | null> | null, audio?: string | null, category?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PagesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PagesQuery = { __typename?: 'Query', pages: { __typename: 'Pages', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'PagesHero', badge?: string | null, titleLine1?: string | null, titleHighlight?: string | null, titleLine3?: string | null, subtitle?: string | null, primaryCta?: string | null, primaryCtaLink?: string | null, secondaryCta?: string | null, secondaryCtaLink?: string | null, achievements?: Array<string | null> | null, impactStats?: Array<{ __typename: 'PagesHeroImpactStats', number?: string | null, label?: string | null } | null> | null, callout?: { __typename: 'PagesHeroCallout', title?: string | null, subtitle?: string | null, cta?: string | null, ctaLink?: string | null } | null } | null, stats?: Array<{ __typename: 'PagesStats', number?: string | null, label?: string | null, description?: string | null } | null> | null, programsSection?: { __typename: 'PagesProgramsSection', title?: string | null, subtitle?: string | null, ctaText?: string | null, ctaLink?: string | null } | null, storiesSection?: { __typename: 'PagesStoriesSection', title?: string | null, subtitle?: string | null, ctaText?: string | null, ctaLink?: string | null } | null, newsletter?: { __typename: 'PagesNewsletter', title?: string | null, subtitle?: string | null, emailPlaceholder?: string | null, buttonText?: string | null, disclaimer?: string | null } | null } };

export type PagesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagesFilter>;
}>;


export type PagesConnectionQuery = { __typename?: 'Query', pagesConnection: { __typename?: 'PagesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PagesConnectionEdges', cursor: string, node?: { __typename: 'Pages', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'PagesHero', badge?: string | null, titleLine1?: string | null, titleHighlight?: string | null, titleLine3?: string | null, subtitle?: string | null, primaryCta?: string | null, primaryCtaLink?: string | null, secondaryCta?: string | null, secondaryCtaLink?: string | null, achievements?: Array<string | null> | null, impactStats?: Array<{ __typename: 'PagesHeroImpactStats', number?: string | null, label?: string | null } | null> | null, callout?: { __typename: 'PagesHeroCallout', title?: string | null, subtitle?: string | null, cta?: string | null, ctaLink?: string | null } | null } | null, stats?: Array<{ __typename: 'PagesStats', number?: string | null, label?: string | null, description?: string | null } | null> | null, programsSection?: { __typename: 'PagesProgramsSection', title?: string | null, subtitle?: string | null, ctaText?: string | null, ctaLink?: string | null } | null, storiesSection?: { __typename: 'PagesStoriesSection', title?: string | null, subtitle?: string | null, ctaText?: string | null, ctaLink?: string | null } | null, newsletter?: { __typename: 'PagesNewsletter', title?: string | null, subtitle?: string | null, emailPlaceholder?: string | null, buttonText?: string | null, disclaimer?: string | null } | null } | null } | null> | null } };

export type ProgramsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProgramsQuery = { __typename?: 'Query', programs: { __typename: 'Programs', id: string, title: string, heroImage?: string | null, body?: any | null, category?: string | null, impactMetric?: string | null, impactValue?: string | null, impactUnit?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProgramsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProgramsFilter>;
}>;


export type ProgramsConnectionQuery = { __typename?: 'Query', programsConnection: { __typename?: 'ProgramsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProgramsConnectionEdges', cursor: string, node?: { __typename: 'Programs', id: string, title: string, heroImage?: string | null, body?: any | null, category?: string | null, impactMetric?: string | null, impactValue?: string | null, impactUnit?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type StoriesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type StoriesQuery = { __typename?: 'Query', stories: { __typename: 'Stories', id: string, title: string, author?: string | null, date?: string | null, location?: string | null, image?: string | null, body?: any | null, category?: string | null, impactMetric?: string | null, impactValue?: string | null, impactUnit?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type StoriesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<StoriesFilter>;
}>;


export type StoriesConnectionQuery = { __typename?: 'Query', storiesConnection: { __typename?: 'StoriesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'StoriesConnectionEdges', cursor: string, node?: { __typename: 'Stories', id: string, title: string, author?: string | null, date?: string | null, location?: string | null, image?: string | null, body?: any | null, category?: string | null, impactMetric?: string | null, impactValue?: string | null, impactUnit?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TeamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamQuery = { __typename?: 'Query', team: { __typename: 'Team', id: string, name?: string | null, title?: string | null, photo?: string | null, bio?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TeamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
}>;


export type TeamConnectionQuery = { __typename?: 'Query', teamConnection: { __typename?: 'TeamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamConnectionEdges', cursor: string, node?: { __typename: 'Team', id: string, name?: string | null, title?: string | null, photo?: string | null, bio?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  title
  date
  author
  excerpt
  primaryCategory
  categories
  tags
  tones
  audio
  category
  heroImage
  body
}
    `;
export const PagesPartsFragmentDoc = gql`
    fragment PagesParts on Pages {
  __typename
  hero {
    __typename
    badge
    titleLine1
    titleHighlight
    titleLine3
    subtitle
    primaryCta
    primaryCtaLink
    secondaryCta
    secondaryCtaLink
    achievements
    impactStats {
      __typename
      number
      label
    }
    callout {
      __typename
      title
      subtitle
      cta
      ctaLink
    }
  }
  stats {
    __typename
    number
    label
    description
  }
  programsSection {
    __typename
    title
    subtitle
    ctaText
    ctaLink
  }
  storiesSection {
    __typename
    title
    subtitle
    ctaText
    ctaLink
  }
  newsletter {
    __typename
    title
    subtitle
    emailPlaceholder
    buttonText
    disclaimer
  }
}
    `;
export const ProgramsPartsFragmentDoc = gql`
    fragment ProgramsParts on Programs {
  __typename
  title
  heroImage
  body
  category
  impactMetric
  impactValue
  impactUnit
}
    `;
export const StoriesPartsFragmentDoc = gql`
    fragment StoriesParts on Stories {
  __typename
  title
  author
  date
  location
  image
  body
  category
  impactMetric
  impactValue
  impactUnit
}
    `;
export const TeamPartsFragmentDoc = gql`
    fragment TeamParts on Team {
  __typename
  name
  title
  photo
  bio
}
    `;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export const PagesDocument = gql`
    query pages($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagesParts
  }
}
    ${PagesPartsFragmentDoc}`;
export const PagesConnectionDocument = gql`
    query pagesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagesFilter) {
  pagesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagesParts
      }
    }
  }
}
    ${PagesPartsFragmentDoc}`;
export const ProgramsDocument = gql`
    query programs($relativePath: String!) {
  programs(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProgramsParts
  }
}
    ${ProgramsPartsFragmentDoc}`;
export const ProgramsConnectionDocument = gql`
    query programsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProgramsFilter) {
  programsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProgramsParts
      }
    }
  }
}
    ${ProgramsPartsFragmentDoc}`;
export const StoriesDocument = gql`
    query stories($relativePath: String!) {
  stories(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...StoriesParts
  }
}
    ${StoriesPartsFragmentDoc}`;
export const StoriesConnectionDocument = gql`
    query storiesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: StoriesFilter) {
  storiesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...StoriesParts
      }
    }
  }
}
    ${StoriesPartsFragmentDoc}`;
export const TeamDocument = gql`
    query team($relativePath: String!) {
  team(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamParts
  }
}
    ${TeamPartsFragmentDoc}`;
export const TeamConnectionDocument = gql`
    query teamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamFilter) {
  teamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamParts
      }
    }
  }
}
    ${TeamPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      },
    pages(variables: PagesQueryVariables, options?: C): Promise<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}> {
        return requester<{data: PagesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesQueryVariables, query: string}, PagesQueryVariables>(PagesDocument, variables, options);
      },
    pagesConnection(variables?: PagesConnectionQueryVariables, options?: C): Promise<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}> {
        return requester<{data: PagesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagesConnectionQueryVariables, query: string}, PagesConnectionQueryVariables>(PagesConnectionDocument, variables, options);
      },
    programs(variables: ProgramsQueryVariables, options?: C): Promise<{data: ProgramsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramsQueryVariables, query: string}> {
        return requester<{data: ProgramsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramsQueryVariables, query: string}, ProgramsQueryVariables>(ProgramsDocument, variables, options);
      },
    programsConnection(variables?: ProgramsConnectionQueryVariables, options?: C): Promise<{data: ProgramsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramsConnectionQueryVariables, query: string}> {
        return requester<{data: ProgramsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProgramsConnectionQueryVariables, query: string}, ProgramsConnectionQueryVariables>(ProgramsConnectionDocument, variables, options);
      },
    stories(variables: StoriesQueryVariables, options?: C): Promise<{data: StoriesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StoriesQueryVariables, query: string}> {
        return requester<{data: StoriesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StoriesQueryVariables, query: string}, StoriesQueryVariables>(StoriesDocument, variables, options);
      },
    storiesConnection(variables?: StoriesConnectionQueryVariables, options?: C): Promise<{data: StoriesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StoriesConnectionQueryVariables, query: string}> {
        return requester<{data: StoriesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: StoriesConnectionQueryVariables, query: string}, StoriesConnectionQueryVariables>(StoriesConnectionDocument, variables, options);
      },
    team(variables: TeamQueryVariables, options?: C): Promise<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}> {
        return requester<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}, TeamQueryVariables>(TeamDocument, variables, options);
      },
    teamConnection(variables?: TeamConnectionQueryVariables, options?: C): Promise<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}> {
        return requester<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}, TeamConnectionQueryVariables>(TeamConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  